USE [master]
GO

/****** Object:  Database [StateValidationTables]    Script Date: 3/1/2017 3:19:28 PM ******/
CREATE DATABASE [StateValidationTables] ON  PRIMARY 
( NAME = N'StateValidationTables', FILENAME = N'F:\SQLServer\Data\StateValidationTables.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'StateValidationTables_log', FILENAME = N'F:\SQLServer\Data\StateValidationTables_log.ldf' , SIZE = 29696KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StateValidationTables] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StateValidationTables].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StateValidationTables] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StateValidationTables] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StateValidationTables] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StateValidationTables] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StateValidationTables] SET ARITHABORT OFF 
GO

ALTER DATABASE [StateValidationTables] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StateValidationTables] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StateValidationTables] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StateValidationTables] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StateValidationTables] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StateValidationTables] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StateValidationTables] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StateValidationTables] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StateValidationTables] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StateValidationTables] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StateValidationTables] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StateValidationTables] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StateValidationTables] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StateValidationTables] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StateValidationTables] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StateValidationTables] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StateValidationTables] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StateValidationTables] SET RECOVERY FULL 
GO

ALTER DATABASE [StateValidationTables] SET  MULTI_USER 
GO

ALTER DATABASE [StateValidationTables] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StateValidationTables] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StateValidationTables] SET  READ_WRITE 
GO


